In [1]:
open(r"D:\Coding_py_c_vscode\hello.py",'r')

<_io.TextIOWrapper name='D:\\Coding_py_c_vscode\\hello.py' mode='r' encoding='cp936'>

In [3]:
with open(r"D:\Coding_py_c_vscode\hello.py",'r',encoding = 'utf-8') as file:
    content = file.read()
    print(content)

def say_hello():
    print("Hello from my module!")


In [ ]:
data = b'\x00\x01\x02\x03'
with open('example.bin','wb') as file:
    file.write(data)
    
with open('example.bin','rb') as file:
    content = file.read()
    print(content)

In [ ]:
import csv

with open('data.csv','r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

In [ ]:
import csv

rows = [['中文','age'],['minhaohui',24],['sunzhengs',19]]
with open('data.csv','w',newline='',encoding = 'utf-8') as file:
    writer = csv.writer(file)
    writer.writerows(rows)

In [6]:
#OS示例
import os

#获取当前工作目录
current_directory = os.getcwd()
print("Current Directory:",current_directory)

#列出目录内容
list_dir = os.listdir('.')
print("Directory content",list_dir)

#创建新目录
if not os.path.exists('new_dir'):
    os.makedirs('new_dir')

Current Directory: D:\Coding_py_c_vscode
Directory content ['.ipynb_checkpoints', 'app.log', 'Genshin test.ipynb', 'hello.py', 'Honkai3.ipynb', 'run.py', 'test.txt', 'utils.py', '__pycache__']


In [5]:
import os

os.getcwd()

'D:\\Coding_py_c_vscode'

In [7]:
list_dir = os.listdir('.')
list_dir

['.ipynb_checkpoints',
 'app.log',
 'Genshin test.ipynb',
 'hello.py',
 'Honkai3.ipynb',
 'new_dir',
 'run.py',
 'test.txt',
 'utils.py',
 '__pycache__']

In [11]:
#创建新目录（文件夹）
if not os.path.exists('nnew_dir'):
    os.makedirs('nnew_dir')

In [12]:
import logging

#配置日志设置
logging.basicConfig(filename = 'app.log',level=logging.INFO,format='%(asctime)s %(message)s')

#记录日志信息
logging.info('Info message')
logging.warning('Warning message')

In [14]:
from joblib import dump,load
import numpy as np

#创建一个大型的Numpy数组
array = np.random.randn(1000,1000)

#使用joblib保存数组
dump(array,'large_array.joblib')

#加载保存的数组
loaded_array = load('large_array.joblib')

print(loaded_array)

[[ 0.88813854 -0.23214655 -1.32922473 ...  0.56204779 -0.93446119
   1.21201384]
 [-0.55860247 -0.22172659  1.86360997 ...  0.03685548  0.37737039
   0.56059842]
 [-1.33839837 -2.39475576  2.23388218 ... -0.80179358 -0.05359085
  -0.56503462]
 ...
 [ 0.2235564   0.72548218 -0.01031522 ... -0.3977604   0.85509783
  -0.67202477]
 [-0.190542   -0.44750787 -1.58035779 ...  1.77193105  0.20097994
  -0.25427076]
 [-0.40400232  1.48313009 -0.2856596  ...  0.52719815 -0.24439967
  -0.73167608]]


In [15]:
import numpy as np

#从Python列表中创建数组
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [19]:
#创建全0数组
np.zeros((3,3))
#创建全1数组并乘2
np.ones((9,9))*2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [20]:
#创建等差数组
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
arr = np.arange(12).reshape(6,2)

In [26]:
arr.shape

(6, 2)

In [27]:
arr[0,1]
# ls[0][1]

1

In [28]:
arr[1][1]

3

In [30]:
arr[:2:1,:1]

array([[0],
       [2]])

In [ ]:
#布尔索引
#创建一个随机数组
data = np.random.randn(5,5)
#使用布尔索引选择大于0的元素
positive_data = data[data > 0]
print("Positive elements:\n",positive_data)

In [ ]:
#花式索引
#创建一个随机数组
data = np.arange(25).reshape(5,5)
#使用花式索引重新排列数组的行
rearanged_data = data[[4,2,1,3,0]]
print("Rearanged rows:\n",rearanged_data)
#使用花式索引同时选择特定的行和列
selected_data = data[[4,2,1],[0,2,3]]
print("Selected elements:\n",selected_data)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])  # 创建一个示例数组

# 加法
result = np.add(arr, 2)  # 对数组的每个元素都加上2
print("加法结果：", result)

# 减法
result = np.subtract(arr, 2)  # 对数组的每个元素都减去2
print("减法结果：", result)

# 乘法
result = np.multiply(arr, 2)  # 数组的每个元素都乘以2
print("乘法结果：", result)

# 除法
result = np.divide(arr, 2)  # 数组的每个元素都除以2
print("除法结果：", result)

# 幂运算
result = np.power(arr, 2)  # 数组的每个元素都平方
print("幂运算结果：", result)

# 平方根
result = np.sqrt(arr)  # 数组的每个元素都求平方根
print("平方根结果：", result)

# 求正弦值
result = np.sin(arr)  # 数组的每个元素都求正弦值
print("正弦值结果：", result)

# 求余弦值
result = np.cos(arr)  # 数组的每个元素都求余弦值
print("余弦值结果：", result)

# 求自然对数
result = np.log(arr)  # 数组的每个元素都求自然对数
print("自然对数结果：", result)

# 求指数函数
result = np.exp(arr)  # 数组的每个元素都求指数函数
print("指数函数结果：", result)


In [31]:
import numpy as np

arr1 = np.array([1, 2, 3])  # 创建第一个数组
arr2 = np.array([4, 5, 6])  # 创建第二个数组

# 数组加法
result_add = np.add(arr1, arr2)  # 对两个数组进行逐元素相加
print("数组加法结果：", result_add)

# 数组乘法
result_multiply = np.multiply(arr1, arr2)  # 对两个数组进行逐元素相乘
print("数组乘法结果：", result_multiply)


数组加法结果： [5 7 9]
数组乘法结果： [ 4 10 18]


In [32]:
import numpy as np

# 创建一个形状为 (3, 3) 的二维数组
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# 创建一个形状为 (3,) 的一维数组
arr2 = np.array([10, 20, 30])

# 使用广播机制将一维数组与二维数组相加
result = arr1 + arr2
print("广播机制相加结果：")
print(result)


广播机制相加结果：
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
import numpy as np

# 创建一个示例数组
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 求所有元素的和
sum_all = np.sum(arr)
print("所有元素的和：", sum_all)

# 求每列的和
sum_axis0 = np.sum(arr, axis=0)
print("每列的和：", sum_axis0)

# 求每行的和
sum_axis1 = np.sum(arr, axis=1)
print("每行的和：", sum_axis1)

# 求所有元素的平均值
mean_value = np.mean(arr)
print("所有元素的平均值：", mean_value)

# 求每列的平均值
mean_axis0 = np.mean(arr, axis=0)
print("每列的平均值：", mean_axis0)

# 求每行的平均值
mean_axis1 = np.mean(arr, axis=1)
print("每行的平均值：", mean_axis1)

# 求所有元素的标准差
std_dev = np.std(arr)
print("所有元素的标准差：", std_dev)

# 求每列的标准差
std_dev_axis0 = np.std(arr, axis=0)
print("每列的标准差：", std_dev_axis0)

# 求每行的标准差
std_dev_axis1 = np.std(arr, axis=1)
print("每行的标准差：", std_dev_axis1)


In [ ]:
import numpy as np

# 创建两个示例矩阵
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# 对矩阵进行乘法运算
C = A @ B
print("矩阵乘法结果：")
print(C)
# @ = time 叉乘
# * = dot 点乘

In [37]:
import pandas as pd

# 从列表创建 Series
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

# 从字典创建 DataFrame
data = {'Name': ['Tom', 'Jerry', 'Mickey', 'Minnie'],
        'Age': [25, 30, 35, 40]}
df = pd.DataFrame(data)
print(df)


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
     Name  Age
0     Tom   25
1   Jerry   30
2  Mickey   35
3  Minnie   40


In [38]:
dates = pd.data_range('20230101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))

AttributeError: module 'pandas' has no attribute 'data_range'

In [39]:
df_csv = pd.read_csv('example.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'example.csv'

In [34]:
pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))

NameError: name 'dates' is not defined

In [41]:
# 导入urllib库的urlopen函数
from urllib.request import urlopen

# 使用urlopen函数打开指定网址，并将返回的对象赋值给html变量
html = urlopen("https://www.baidu.com")

# 读取html对象的内容，并将字节流解码为字符串
html_text = bytes.decode(html.read())

# 打印获取到的网页内容
print(html_text)


<html>
<head>
	<script>
		location.replace(location.href.replace("https://","http://"));
	</script>
</head>
<body>
	<noscript><meta http-equiv="refresh" content="0;url=http://www.baidu.com/"></noscript>
</body>
</html>


In [43]:
# -*- codeing = utf-8 -*-
from bs4 import BeautifulSoup  # 网页解析，获取数据
import re  # 正则表达式，进行文字匹配`
import urllib.request, urllib.error  # 制定URL，获取网页数据
import xlwt  # 进行excel操作
#import sqlite3  # 进行SQLite数据库操作

findLink = re.compile(r'<a href="(.*?)">')  # 创建正则表达式对象，标售规则   影片详情链接的规则
findImgSrc = re.compile(r'<img.*src="(.*?)"', re.S)
findTitle = re.compile(r'<span class="title">(.*)</span>')
findRating = re.compile(r'<span class="rating_num" property="v:average">(.*)</span>')
findJudge = re.compile(r'<span>(\d*)人评价</span>')
findInq = re.compile(r'<span class="inq">(.*)</span>')
findBd = re.compile(r'<p class="">(.*?)</p>', re.S)


def main():
    baseurl = "https://movie.douban.com/top250?start="  #要爬取的网页链接
    # 1.爬取网页
    datalist = getData(baseurl)
    savepath = "豆瓣电影Top250.xls"    #当前目录新建XLS，存储进去
    # dbpath = "movie.db"              #当前目录新建数据库，存储进去
    # 3.保存数据
    saveData(datalist,savepath)      #2种存储方式可以只选择一种
    # saveData2DB(datalist,dbpath)


# 爬取网页
def getData(baseurl):
    datalist = []  #用来存储爬取的网页信息
    for i in range(0, 10):  # 调用获取页面信息的函数，10次
        url = baseurl + str(i * 25)
        html = askURL(url)  # 保存获取到的网页源码
        # 2.逐一解析数据
        soup = BeautifulSoup(html, "html.parser")
        for item in soup.find_all('div', class_="item"):  # 查找符合要求的字符串
            data = []  # 保存一部电影所有信息
            item = str(item)
            link = re.findall(findLink, item)[0]  # 通过正则表达式查找
            data.append(link)
            imgSrc = re.findall(findImgSrc, item)[0]
            data.append(imgSrc)
            titles = re.findall(findTitle, item)
            if (len(titles) == 2):
                ctitle = titles[0]
                data.append(ctitle)
                otitle = titles[1].replace("/", "")  #消除转义字符
                data.append(otitle)
            else:
                data.append(titles[0])
                data.append(' ')
            rating = re.findall(findRating, item)[0]
            data.append(rating)
            judgeNum = re.findall(findJudge, item)[0]
            data.append(judgeNum)
            inq = re.findall(findInq, item)
            if len(inq) != 0:
                inq = inq[0].replace("。", "")
                data.append(inq)
            else:
                data.append(" ")
            bd = re.findall(findBd, item)[0]
            bd = re.sub('<br(\s+)?/>(\s+)?', "", bd)
            bd = re.sub('/', "", bd)
            data.append(bd.strip())
            datalist.append(data)

    return datalist


# 得到指定一个URL的网页内容
def askURL(url):
    head = {  # 模拟浏览器头部信息，向豆瓣服务器发送消息
        "User-Agent": "Mozilla / 5.0(Windows NT 10.0; Win64; x64) AppleWebKit / 537.36(KHTML, like Gecko) Chrome / 80.0.3987.122  Safari / 537.36"
    }
    # 用户代理，表示告诉豆瓣服务器，我们是什么类型的机器、浏览器（本质上是告诉浏览器，我们可以接收什么水平的文件内容）

    request = urllib.request.Request(url, headers=head)
    html = ""
    try:
        response = urllib.request.urlopen(request)
        html = response.read().decode("utf-8")
    except urllib.error.URLError as e:
        if hasattr(e, "code"):
            print(e.code)
        if hasattr(e, "reason"):
            print(e.reason)
    return html


# 保存数据到表格
def saveData(datalist,savepath):
    print("save.......")
    book = xlwt.Workbook(encoding="utf-8",style_compression=0) #创建workbook对象
    sheet = book.add_sheet('豆瓣电影Top250', cell_overwrite_ok=True) #创建工作表
    col = ("电影详情链接","图片链接","影片中文名","影片外国名","评分","评价数","概况","相关信息")
    for i in range(0,8):
        sheet.write(0,i,col[i])  #列名
    for i in range(0,250):
        # print("第%d条" %(i+1))       #输出语句，用来测试
        data = datalist[i]
        for j in range(0,8):
            sheet.write(i+1,j,data[j])  #数据
    book.save(savepath) #保存

# def saveData2DB(datalist,dbpath):
#     init_db(dbpath)
#     conn = sqlite3.connect(dbpath)
#     cur = conn.cursor()
#     for data in datalist:
#             for index in range(len(data)):
#                 if index == 4 or index == 5:
#                     continue
#                 data[index] = '"'+data[index]+'"'
#             sql = '''
#                     insert into movie250(
#                     info_link,pic_link,cname,ename,score,rated,instroduction,info)
#                     values (%s)'''%",".join(data)
#             # print(sql)     #输出查询语句，用来测试
#             cur.execute(sql)
#             conn.commit()
#     cur.close
#     conn.close()


# def init_db(dbpath):
#     sql = '''
#         create table movie250(
#         id integer  primary  key autoincrement,
#         info_link text,
#         pic_link text,
#         cname varchar,
#         ename varchar ,
#         score numeric,
#         rated numeric,
#         instroduction text,
#         info text
#         )
#
#
#     '''  #创建数据表
#     conn = sqlite3.connect(dbpath)
#     cursor = conn.cursor()
#     cursor.execute(sql)
#     conn.commit()
#     conn.close()

# 保存数据到数据库



if __name__ == "__main__":  # 当程序执行时
    # 调用函数
     main()
    # init_db("movietest.db")
     print("爬取完毕！")



save.......
爬取完毕！
